.PHONY = run myhi clean
cc := gcc

run:
	@${cc} william_hello.c -o william_hello
	@./william_hello
william_hello:
	@${cc} william_hello.c -o william_hello
clean:
	@rm -rvf william_hello.o william_hello
